---
title: "Motif Test"
author: "Paolo Cozzi"
date: today
toc: true
number-sections: true
cache: true
format:
  html:
    code-line-numbers: true
    html-math-method: katex
    df-print: paged
    code-fold: true
    toc-depth: 5
    embed-resources: true  # Embed all resources directly into the HTML file
knitr:
  opts_chunk:
    dpi: 100
editor: source
---

```{r setup, warning=FALSE}
library("here")
library("data.table")
library("ggplot2")
library("dplyr")
```

## Read data from methylong output

Directly filter out data (since it's very large) using `awk` to keep only rows
with `score >= 10` and `count_modified > 0`. This will reduce the size of the
data significantly before loading it into R.

```{r read-data}
file_path <- here::here("output_methylong-5mC_5hmC/ont/A19_jun/pileup", "A19_jun.bed.gz")
cmd <- sprintf("zcat %s | awk 'NR==1 || ($5 >= 10 && $12 > 0)'", shQuote(file_path))
bed100 <- data.table::fread(cmd = cmd, sep = "\t", header = TRUE)
summary(bed100)
```

## Make a picture

```{r make-picture}
bed100_plot <- ggplot(bed100, aes(name, percent_modified)) +
    geom_boxplot() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
bed100_plot
```
